# Generated by Django 4.2.13 on 2024-07-02 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='amount',
            new_name='Amount',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='description',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='email',
            new_name='Email',
        ),
        migrations.AddField(
            model_name='payment',
            name='Name',
            field=models.CharField(default='John', max_length=255),
        ),
    ]
