# Generated by Django 4.2.13 on 2024-07-08 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_stripe_payment_intent_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='stripe_payment_intent_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='address',
            field=models.CharField(blank=True, max_length=264),
        ),
        migrations.AddField(
            model_name='payment',
            name='city',
            field=models.CharField(blank=True, max_length=264),
        ),
        migrations.AddField(
            model_name='payment',
            name='country',
            field=models.CharField(blank=True, max_length=264),
        ),
        migrations.AddField(
            model_name='payment',
            name='zipcode',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
