# Generated by Django 4.2.13 on 2024-07-08 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_remove_payment_stripe_payment_intent_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='city',
            field=models.CharField(blank=True, choices=[('NYC', 'New York City'), ('LAX', 'Los Angeles'), ('CHI', 'Chicago'), ('HOU', 'Houston'), ('PHX', 'Phoenix'), ('TOR', 'Toronto'), ('VAN', 'Vancouver'), ('MTL', 'Montreal'), ('LDN', 'London'), ('MAN', 'Manchester'), ('SYD', 'Sydney'), ('MEL', 'Melbourne'), ('BER', 'Berlin'), ('MUC', 'Munich'), ('PAR', 'Paris'), ('LYO', 'Lyon'), ('ROM', 'Rome'), ('MIL', 'Milan'), ('MAD', 'Madrid'), ('BCN', 'Barcelona'), ('TOK', 'Tokyo'), ('OSA', 'Osaka'), ('BJS', 'Beijing'), ('SHA', 'Shanghai'), ('DEL', 'Delhi'), ('MUM', 'Mumbai'), ('RIO', 'Rio de Janeiro'), ('SAO', 'Sao Paulo'), ('MOW', 'Moscow'), ('SPB', 'Saint Petersburg'), ('MEX', 'Mexico City'), ('GDL', 'Guadalajara'), ('JHB', 'Johannesburg'), ('CPT', 'Cape Town'), ('LOS', 'Lagos'), ('CAI', 'Cairo'), ('BUE', 'Buenos Aires'), ('SCL', 'Santiago'), ('BOG', 'Bogota'), ('STO', 'Stockholm'), ('OSL', 'Oslo'), ('CPH', 'Copenhagen'), ('HEL', 'Helsinki'), ('WAW', 'Warsaw'), ('IST', 'Istanbul'), ('SEL', 'Seoul'), ('SIN', 'Singapore'), ('KUL', 'Kuala Lumpur'), ('BKK', 'Bangkok')], max_length=264),
        ),
        migrations.AlterField(
            model_name='payment',
            name='country',
            field=models.CharField(blank=True, choices=[('USA', 'United States'), ('CAN', 'Canada'), ('UK', 'United Kingdom'), ('AUS', 'Australia'), ('GER', 'Germany'), ('FRA', 'France'), ('ITA', 'Italy'), ('ESP', 'Spain'), ('JPN', 'Japan'), ('CHN', 'China'), ('IND', 'India'), ('BRA', 'Brazil'), ('RUS', 'Russia'), ('MEX', 'Mexico'), ('RSA', 'South Africa'), ('NIG', 'Nigeria'), ('EGY', 'Egypt'), ('ARG', 'Argentina'), ('CHL', 'Chile'), ('COL', 'Colombia'), ('SWE', 'Sweden'), ('NOR', 'Norway'), ('DEN', 'Denmark'), ('FIN', 'Finland'), ('POL', 'Poland'), ('TUR', 'Turkey'), ('KOR', 'South Korea'), ('SGP', 'Singapore'), ('MYS', 'Malaysia'), ('THA', 'Thailand'), ('VNM', 'Vietnam'), ('PHL', 'Philippines'), ('IDN', 'Indonesia'), ('NZL', 'New Zealand'), ('SAU', 'Saudi Arabia'), ('ISR', 'Israel'), ('UAE', 'United Arab Emirates'), ('IRN', 'Iran'), ('PAK', 'Pakistan'), ('BGD', 'Bangladesh'), ('UKR', 'Ukraine'), ('BEL', 'Belgium'), ('NLD', 'Netherlands'), ('CHE', 'Switzerland'), ('AUT', 'Austria'), ('GRC', 'Greece'), ('HUN', 'Hungary'), ('CZE', 'Czech Republic'), ('PRT', 'Portugal'), ('ROU', 'Romania')], max_length=264),
        ),
    ]
