# Generated by Django 4.2.13 on 2024-07-08 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_alter_payment_city_alter_payment_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='city',
            field=models.CharField(blank=True, choices=[('NYC', 'New York City'), ('LAX', 'Los Angeles'), ('CHI', 'Chicago'), ('HOU', 'Houston'), ('PHX', 'Phoenix'), ('TOR', 'Toronto'), ('VAN', 'Vancouver'), ('MTL', 'Montreal'), ('LDN', 'London'), ('MAN', 'Manchester'), ('SYD', 'Sydney'), ('MEL', 'Melbourne'), ('BER', 'Berlin'), ('MUC', 'Munich'), ('PAR', 'Paris'), ('LYO', 'Lyon'), ('ROM', 'Rome'), ('MIL', 'Milan'), ('MAD', 'Madrid'), ('BCN', 'Barcelona'), ('TOK', 'Tokyo'), ('OSA', 'Osaka'), ('BJS', 'Beijing'), ('SHA', 'Shanghai'), ('DEL', 'Delhi'), ('MUM', 'Mumbai'), ('RIO', 'Rio de Janeiro'), ('SAO', 'Sao Paulo'), ('MOW', 'Moscow'), ('SPB', 'Saint Petersburg'), ('MEX', 'Mexico City'), ('GDL', 'Guadalajara'), ('JHB', 'Johannesburg'), ('CPT', 'Cape Town'), ('LOS', 'Lagos'), ('CAI', 'Cairo'), ('BUE', 'Buenos Aires'), ('SCL', 'Santiago'), ('BOG', 'Bogota'), ('STO', 'Stockholm'), ('OSL', 'Oslo'), ('CPH', 'Copenhagen'), ('HEL', 'Helsinki'), ('WAW', 'Warsaw'), ('IST', 'Istanbul'), ('SEL', 'Seoul'), ('SIN', 'Singapore'), ('KUL', 'Kuala Lumpur'), ('BKK', 'Bangkok'), ('HAN', 'Hanoi'), ('HCM', 'Ho Chi Minh City')], default='TOR', max_length=264),
        ),
    ]
