# Generated by Django 4.2.13 on 2024-07-22 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_order_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='Name',
            field=models.CharField(default='test', max_length=255),
        ),
    ]
