# Generated by Django 4.2.13 on 2024-07-22 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_alter_payment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='Email',
            field=models.EmailField(default='test@greencart.ca', max_length=254),
        ),
        migrations.AlterField(
            model_name='payment',
            name='Name',
            field=models.CharField(default='Jack Ryan', max_length=255),
        ),
        migrations.AlterField(
            model_name='payment',
            name='address',
            field=models.CharField(blank=True, default='300 Ouellette Avenue', max_length=264),
        ),
        migrations.AlterField(
            model_name='payment',
            name='city',
            field=models.CharField(blank=True, choices=[('NYC', 'New York City'), ('LAX', 'Los Angeles'), ('CHI', 'Chicago'), ('HOU', 'Houston'), ('PHX', 'Phoenix'), ('TOR', 'Toronto'), ('VAN', 'Vancouver'), ('MTL', 'Montreal'), ('LDN', 'London'), ('MAN', 'Manchester'), ('SYD', 'Sydney'), ('MEL', 'Melbourne'), ('BER', 'Berlin'), ('MUC', 'Munich'), ('PAR', 'Paris'), ('LYO', 'Lyon'), ('ROM', 'Rome'), ('MIL', 'Milan'), ('MAD', 'Madrid'), ('BCN', 'Barcelona'), ('TOK', 'Tokyo'), ('OSA', 'Osaka'), ('BJS', 'Beijing'), ('SHA', 'Shanghai'), ('DEL', 'Delhi'), ('MUM', 'Mumbai'), ('RIO', 'Rio de Janeiro'), ('SAO', 'Sao Paulo'), ('MOW', 'Moscow'), ('SPB', 'Saint Petersburg'), ('MEX', 'Mexico City'), ('GDL', 'Guadalajara'), ('JHB', 'Johannesburg'), ('CPT', 'Cape Town'), ('LOS', 'Lagos'), ('CAI', 'Cairo'), ('BUE', 'Buenos Aires'), ('SCL', 'Santiago'), ('BOG', 'Bogota'), ('STO', 'Stockholm'), ('OSL', 'Oslo'), ('CPH', 'Copenhagen'), ('HEL', 'Helsinki'), ('WAW', 'Warsaw'), ('IST', 'Istanbul'), ('SEL', 'Seoul'), ('SIN', 'Singapore'), ('KUL', 'Kuala Lumpur'), ('BKK', 'Bangkok'), ('HAN', 'Hanoi'), ('HCM', 'Ho Chi Minh City'), ('WIN', 'Windsor')], default='WIN', max_length=264),
        ),
        migrations.AlterField(
            model_name='payment',
            name='zipcode',
            field=models.CharField(blank=True, default='N9A 7B4', max_length=10),
        ),
    ]
