# Generated by Django 5.0.6 on 2024-07-01 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Support', '0002_faq_complaint'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('type', models.CharField(choices=[('order_status', 'Order Status'), ('order_delivery', 'Order Delivery'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='query_attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
