# Generated by Django 5.0.6 on 2024-07-22 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Support', '0004_query_ticket_number_ticketstatus_delete_complaint'),
    ]

    operations = [
        migrations.CreateModel(
            name='faqCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='faq',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Support.faqcategory'),
        ),
    ]
