# Generated by Django 4.2.13 on 2024-07-15 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GreenCartEcom', '0002_offer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='navCategories',
        ),
    ]
