# Generated by Django 4.2.13 on 2024-06-30 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='expiry',
            field=models.IntegerField(default=3),
        ),
    ]
