# Generated by Django 4.2.13 on 2024-07-01 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0002_product_image'),
        ('Shop', '0003_product_image'),
    ]

    operations = [
    ]
