# Generated by Django 4.2.13 on 2024-07-01 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0002_product_expiry'),
        ('Shop', '0005_product_created_at_product_updated_at_and_more'),
    ]

    operations = [
    ]
