# Generated by Django 4.2.13 on 2024-07-02 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0006_merge_20240701_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='user_id',
            field=models.CharField(default='1', max_length=10),
        ),
    ]
