# Generated by Django 4.2.13 on 2024-07-16 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0009_reviews_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='expiry_status',
            field=models.BooleanField(default=False),
        ),
    ]
