# Generated by Django 4.2.13 on 2024-07-16 21:30


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0010_product_expiry_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='expiry_status',
        ),
    ]
