# Generated by Django 4.2.13 on 2024-07-22 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_to_cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='user_id',
            field=models.CharField(default='1', max_length=10),
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='user_id',
            field=models.CharField(default='1', max_length=10),
        ),
    ]
