# Generated by Django 4.2.13 on 2024-06-28 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_alter_userprofile_address_line_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='address_line_2',
            field=models.CharField(blank=True, default='-', max_length=255),
        ),
    ]
